name: gh-pages publisher 🚀

on:
  push:
    branches: [ master ]

jobs:
  publish-gh-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: gh-pages -d . -r https://$GH_TOKEN@github.com/mvonballmo/APE_Docs.git
    env:
      GH_TOKEN: ${{secrets.SECRET_GITHUB_TOKEN}}
